language: php
sudo: required
dist: trusty

php:
  - 7.4

addons:
  chrome: stable

install:
  - rm .env.example
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - touch ./database/database.sqlite
  - php artisan key:generate
  - php artisan migrate --database=sqlite --no-interaction
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose
